function [control_board,Aea, Aea_Ref, Mot_enc, YPR] = csv_to_timeseries(path)

    control_board = readtable(path);
    control_board(1, :) = []; 
    Aea = timeseries([control_board.Aea0_Ref - control_board.Aea0_Err, ...
                  control_board.Aea1_Ref - control_board.Aea1_Err,...
                  control_board.Aea2_Ref - control_board.Aea2_Err], ...
                  control_board.Time, 'Name','Aea, deg');
    Aea_Ref = timeseries([control_board.Aea0_Ref, ...
                  control_board.Aea1_Ref,...
                  control_board.Aea2_Ref], ...
                  control_board.Time, 'Name','Aea_Ref, deg');
    
    Mot_enc = timeseries([control_board.Mot0_Enc ,control_board.Mot1_Enc, control_board.Mot2_Enc], control_board.Time, 'Name','Motor_Enc, deg');
    
    YPR = timeseries( [control_board.Yaw, control_board.Roll, control_board.Pitch], control_board.Time, 'Name','YPR, deg');
end

